### ISSUE TITLE
question: [How can I save the weights in quant_pytorch_mode.bin with INT16 or INT32 tensor format, in Q8BERT]

### ISSUE THREAD

**Issue by Shinonome233** [IntelLabs/nlp-architect#161]
I am using the Q8BERT to do some quantization work. And I am thinking about quantizing the BERT into more than 8bit. I printed the quant_pytorch_model.bin, and the quantized weights are INT8 tensor format. How can I change it into INT16 or INT32 when I save the quantized model? Thanks for your help.

**Comment by ofirzaf** [comment]
Hi, unfortunately we didn't implement a way to export Q8BERT in other precisions except in 8bit. However, this can be achieved by changing the following line of code to `.short()` instead of `.char()`
https://github.com/NervanaSystems/nlp-architect/blob/c015f711870ce20c59341c7a26ece9c3e239570f/nlp_architect/nn/torch/quantization.py#L199
If you happen to program the logic for determining in which precision the weight should be outputted automatically we would love to add it to our code.
